trigger:
  branches:
    include:
      - master

pool:
  name: Default

variables:
  buildConfiguration: 'Release'
  artifactName: 'MyWebApp'  # Change this to the desired name of your artifact
  publishFolder: '$(Build.ArtifactStagingDirectory)/publish'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: |
    dotnet publish --configuration $(buildConfiguration) --output $(publishFolder) --no-build --no-restore
  displayName: 'Publish Web App'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(publishFolder)'
    artifact: '$(artifactName)'
  displayName: 'Publish Artifact'

- script: |
    az artifacts universal publish --organization $(System.CollectionUri) --scope project --feed feedname --name $(artifactName) --version $(buildConfiguration) --description "Published from Azure Pipelines"
    # Optionally, you can delete the local published folder if it's not needed after the artifact is pushed to Azure Artifacts.
    rm -rf $(publishFolder)
  displayName: 'Upload to Azure Artifacts'
